export const chaturbateCountries: Record<string, string> = {
  AT: "Austrija",
  AU: "Australija",
  BE: "Belgija",
  CA: "Kanada",
  CH: "Švicarska",
  DE: "Njemačka",
  DK: "Danska",
  FI: "Finska",
  FK: "Falklandski Otoci (Malvini)",
  FO: "Farski Otoci",
  FR: "Francuska",
  GB: "Ujedinjeno Kraljevstvo",
  GG: "Guernsey",
  GI: "Gibraltar",
  GL: "Grenland",
  IE: "Irska",
  IS: "Island",
  JE: "Jersey",
  JP: "Japan",
  LI: "Lihtenštajn",
  LU: "Luksemburg",
  NL: "Nizozemska",
  NO: "Norveška",
  NZ: "Novi Zeland",
  QA: "Katar",
  SE: "Švedska",
  SG: "Singapur",
  SM: "San Marino",
  UM: "Američki Manji Vanjski Otoci",
  US: "Sjedinjene Američke Države",
  VI: "Američki Djevičanski Otoci",
  AE: "Ujedinjeni Arapski Emirati",
  AW: "Aruba",
  BN: "Brunej",
  BR: "Brazil",
  BS: "Bahami",
  CY: "Cipar",
  ES: "Španjolska",
  GQ: "Ekvatorska Gvineja",
  GR: "Grčka",
  HK: "Hong Kong",
  IL: "Izrael",
  IM: "Otok Man",
  IT: "Italija",
  KR: "Južna Koreja",
  KW: "Kuvajt",
  KY: "Kajmanski Otoci",
  MO: "Makao",
  PF: "Francuska Polinezija",
  PR: "Portoriko",
  PT: "Portugal",
  SI: "Slovenija",
  VG: "Britanski Djevičanski Otoci",
  AG: "Antigva i Barbuda",
  AI: "Angvila",
  BB: "Barbados",
  BH: "Bahrein",
  CK: "Cookovi Otoci",
  CL: "Čile",
  CZ: "Češka",
  EE: "Estonija",
  GU: "Guam",
  HR: "Hrvatska",
  HU: "Mađarska",
  IN: "Indija",
  KN: "Sveti Kristofor i Nevis",
  LB: "Libanon",
  LT: "Litva",
  LV: "Latvija",
  MP: "Sjeverni Marijanski Otoci",
  MT: "Malta",
  MX: "Meksiko",
  NC: "Nova Kaledonija",
  OM: "Oman",
  PL: "Poljska",
  RU: "Rusija",
  SA: "Saudijska Arabija",
  SC: "Sejšeli",
  SK: "Slovačka",
  TR: "Turska",
  TT: "Trinidad i Tobago",
  TW: "Tajvan",
  UY: "Urugvaj",
  VE: "Venezuela",
  CO: "Kolumbija",
  MN: "Mongolija",
  MU: "Mauricijus",
  PH: "Filipini",
  RO: "Rumunjska",
  TH: "Tajland",
  UA: "Ukrajina",
  AR: "Argentina",
  KE: "Kenija",
};